GET http://localhost:3000/admins

###
GET http://localhost:3000/admins/6092824e4c22863c185d13b9

### 
POST http://localhost:3000/admins
Content-Type: application/json

{
    "email": "orbis@usthb.dz",
    "username": "Orbisclub",
    "password": "sfertery",
    "club_id": 3
}

###
PATCH http://localhost:3000/admins/6092a334f79a542ec4462640
Content-Type: application/json

{
    "email": "microclub@usthb.com"
}

###
DELETE http://localhost:3000/admins/609b8a82fdb8b57cd4abd16b