GET http://localhost:3000/clubs

###
GET http://localhost:3000/clubs/1

###
POST http://localhost:3000/clubs
Content-Type: application/json

{
    "_id": 5,
    "name": "Operations Research Society",
    "position": "d2",
    "logo": "img",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
}

###
PATCH http://localhost:3000/clubs/1
Content-Type: application/json

{
    "name": "OpenMindsClub",
    "description": "philosophie du libre open source"
}

###
DELETE http://localhost:3000/clubs/608db71f6714cabe65a50120