GET http://localhost:3000/participants

###
GET http://localhost:3000/participants/1

###
POST http://localhost:3000/participants
Content-Type: application/json

{
    "username": "cr105ph1nxx",
    "email": "lilia.mehamli@live.com",
    "password": "123456",
    "startingpoint": 1
}

###
PATCH http://localhost:3000/participants/6092aeaf106cac1f74ec21f3
Content-Type: application/json

{
    "email": "lilly.mehamli@live.com"
}

###
DELETE http://localhost:3000/participants/6092b0fa8fe5832dd4e404a9