GET http://localhost:3000/participants

###
GET http://localhost:3000/participants/1

###
POST http://localhost:3000/participants
Content-Type: application/json

{
    "username": "cr105ph1nx",
    "email": "lilia.mehamli@live.com",
    "password": "123456",
    "startingpoint": 1
}

###
PATCH http://localhost:3000/participants/609eab719d1f99abe043adf6
Content-Type: application/json

{
    "email": "lilly.mehamli@live.com"
}

###
DELETE http://localhost:3000/participants/609eb6c40d097bdcb5ad5f9a