GET http://localhost:3000/participantClubs

###
GET http://localhost:3000/participantClubs/608dbdcac7f520d8ed7a72c8

###
POST http://localhost:3000/participantClubs
Content-Type: application/json

{
    "club_id": 1,
    "participant_id": "609a7478acbee02a889fa890",
    "piece": "q"
}

###
PATCH http://localhost:3000/participantClubs/609eb6c40d097bdcb5ad5f9b
Content-Type: application/json

{
    "piece": "r"
}

###
DELETE http://localhost:3000/participantClubs/609f604c4f0004ee29d5023a

### GET PARTICIPANTS IN CURRENT CASE
GET http://localhost:3000/participantClubs/getCurrentParticipants/1
